ocr:
  bucket: "guai"
  region: "us-east-2"

  # GPT-5-nano (latest alias)
  model_id: "gpt-5-nano"
  dpi: 250
  temperature: 0.0
  max_tokens: 2500
  retries: 6

phoenix:
  otlp_endpoint: "http://localhost:4317"
  service_name: "bedrock-pdf-ocr"


























